extensions:
  memory_ballast:
    size_mib: 512
  zpages:
    endpoint: 0.0.0.0:55679

receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:
    timeout: 10s

exporters:
  logging:
    logLevel: debug
  datadog:
    env: poc
    service: customer-service
    version: 0.0.1-SNAPSHOT
    tags: [poc]
    api:
      key: ###############
      site: datadoghq.eu

service:
  pipelines:
    traces:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ logging, datadog ]
  extensions: [ memory_ballast, zpages ]
