server:
  port: 8081
  servlet:
    context-path: /

services:
  customer-service-bff:
    url: localhost:8080
  order-service:
    url: localhost:8082

kafka:
  bootstrap: kafka:9092
  topic: customers-topic
  group: customers-group

springdoc:
  swagger-ui:
    displayRequestDuration: true
    disable-swagger-default-url: true
    csrf:
      enabled: true
    operationsSorter: method #For sorting endpoints by http methods
    tagsSorter: alpha #For sorting tags alphabetically
  api-docs:
    path: /api

spring:
  application:
    name: customer-service
  sleuth:
    otel:
      config:
        trace-id-ratio-based: 1.0
      exporter:
        otlp:
          endpoint: http://otel-collector:4317

  h2:
    console:
      enabled: true
      path: /h2-console
  jackson: 
    default-property-inclusion: NON_NULL

  datasource:
    name: customer-service
    ### In memory H2 connection string
    #jdbc-url: jdbc:h2:mem:customerservice;Mode=postgreSQL
    #username: sa
    # It needs to be empty for h2 (enter sa into h2-console)
    #password: # It needs to be empty for h2
    #type: # It needs to be empty for h2
    #driver-class-name: org.h2.Driver #it has to be populated to avoid "Failed to load driver in either of HikariConfig class loader or Thread context classloader" error
    ### PostgreSQL
    jdbc-url: jdbc:postgresql://localhost:5432/customerservice
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    tlsEnabled: true
    minimum-idle: 10 # The minimum number of established connections that should be kept in the pool at all times.
    maximum-pool-size: 50 # The maximum number of connections that should be kept in the pool at all times.
    idle-timeout: 30000 # The maximum amount of time in milliseconds that a connection is allowed to sit idle in connection pool
    max-lifetime: 60000 # The maximum lifetime of a connection in the pool

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    pageable:
      page-size: 100

  liquibase:
    change-log: classpath:/changelog/db.changelog-master.xml
    enabled: true

management:
  endpoints:
    web:
      base-path: /monitoring
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: 'ALWAYS'
  health: 
    circuitbreakers: 
      enabled: true

---
# need this block for local build even though some params can be left empty
global:
  datasource:
    truststore:
      location: /tmp/postgre.jks #fake placeholder value to avoid local build error
      password:
      content:
      type: JKS
